// Enhanced border options with animation properties
export const BORDER_OPTIONS = [
  { 
    id: 'default', 
    name: 'Default Border', 
    price: 0, 
    color: '#808080', 
    description: 'Reset to the default border based on card rarity',
    animationType: 'none',
    secondaryColor: '#808080',
  },
  { 
    id: 'neon', 
    name: 'Neon Glow', 
    price: 5, 
    color: '#00FF00', 
    description: 'A vibrant neon green glow around your cards',
    animationType: 'pulse',
    secondaryColor: '#00FF88',
  },
  { 
    id: 'gold', 
    name: 'Gold Frame', 
    price: 5, 
    color: '#FFD700', 
    description: 'Luxurious gold frame for your most valuable cards',
    animationType: 'shimmer',
    secondaryColor: '#FFC107',
  },
  { 
    id: 'rainbow', 
    name: 'Rainbow Edge', 
    price: 10, 
    color: '#FF0000', 
    description: 'Colorful rainbow pattern around card edges',
    animationType: 'rotate',
    secondaryColor: '#FF00FF',
  },
  { 
    id: 'fire', 
    name: 'Fire Border', 
    price: 10, 
    color: '#FF4500', 
    description: 'Animated flame effect around your cards',
    animationType: 'flicker',
    secondaryColor: '#FFCC00',
  },
  { 
    id: 'ice', 
    name: 'Ice Frame', 
    price: 10, 
    color: '#ADD8E6', 
    description: 'Cool ice crystal effect for card borders',
    animationType: 'frost',
    secondaryColor: '#E0FFFF',
  },
  { 
    id: 'shadow', 
    name: 'Shadow Aura', 
    price: 10, 
    color: '#800080', 
    description: 'Dark mysterious shadow effect around cards',
    animationType: 'wave',
    secondaryColor: '#4B0082',
  },
]; 